name: Daily Portfolio Reporting
on:
  schedule:
    - cron: '30 20 * * *'  # 5 minutes after market tracker
  workflow_dispatch:
permissions:
  contents: write
jobs:
  generate-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl requests PyYAML python-dateutil
      
      - name: Create output directories
        run: |
          mkdir -p reports
          mkdir -p excel_reports
          mkdir -p backups
      
      - name: Check for reporting script
        run: |
          if [ ! -f "reporting/portfolio_report_generator.py" ]; then
            echo "No reporting script found, skipping report generation"
            exit 0
          fi
      
      - name: Generate daily reports (if script exists)
        run: |
          if [ -f "reporting/portfolio_report_generator.py" ]; then
            cd reporting
            python portfolio_report_generator.py || echo "Report generation failed, continuing"
          else
            echo "No reporting script found, creating placeholder"
            echo "# Daily reports will be generated here" > reports/placeholder.md
          fi
      
      - name: Commit reports
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add reports/ excel_reports/ backups/ || echo "No report files to add"
          if git diff --staged --quiet; then
            echo "No report changes to commit"
          else
            git commit -m "Add daily portfolio reports [skip ci]"
            git push
          fi
