name: Daily Portfolio Reporting
on:
  schedule:
    - cron: '30 20 * * *'   # 10 minutes after market context
  workflow_dispatch:
permissions:
  contents: write
jobs:
  generate-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install reporting dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r reporting/requirements.txt
          
      - name: Create output directories
        run: |
          mkdir -p reports excel_reports backups
          
      - name: Generate daily reports
        run: |
          cd reporting
          python portfolio_report_generator.py
          
      - name: Run portfolio health check
        run: python monitor.py
        
      - name: Commit reports
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add reports/ excel_reports/ backups/
          git commit -m "📋 Daily reports generated - $(date -u +%Y-%m-%d)" || echo "No new reports"
          git push
