name: Daily Portfolio Tracker
on:
  schedule:
    - cron: '20 20 * * *'   # 20:20 UTC daily
  workflow_dispatch:
permissions:
  contents: write
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create required directories
        run: |
          mkdir -p data state docs reports
          
      - name: Run portfolio tracker
        env:
          ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
        run: python main.py
        
      - name: Commit portfolio updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/ docs/ reports/ state/
          git commit -m "📊 Daily portfolio update - $(date -u +%Y-%m-%d)" || echo "No changes to commit"
          git push
